apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions-job
spec:
  schedule: "* 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k8s-test-django-clearsession
            image: django-app:v1
            command: ['python', 'manage.py', 'clearsessions']
            imagePullPolicy: Never
            envFrom:
            - configMapRef:
                name: config-test-app
          restartPolicy: OnFailure