apiVersion : v1
kind: Pod
metadata:
  name: django-clearsession-pod
  labels:
    app : k8s-deployment
spec:
  containers:
  - args:
    - /usr/local/bin/python
    - manage.py
    - clearsessions
    name : k8s-test-django-clearsession
    image: django-app:v1
    envFrom:
    - configMapRef:
        name: config-test-app
  restartPolicy: Never