apiVersion: v1
kind: ConfigMap
metadata:
  name: config-test-app
  namespace: default
data:
  DATABASE_URL: postgres://test_k8s:OwOtBep9Frut@172.18.0.2:5432/test_k8s
  SECRET_KEY: зачемтоптатьмоюлюбовьеёитакпочтинестало
  DEBUG: 'True'
  ALLOWED_HOSTS: star-burger.test