DATABASE_URL=postgres://test_k8s:OwOtBep9Frut@172.18.0.2:5432/test_k8s
ALLOWED_HOSTS=10.111.137.26,192.168.59.102,10.105.88.18,star-burger.test
SECRET_KEY=зачемтоптатьмоюлюбовьеёитакпочтинестало
DEBUG=False